#!/bin/bash

root=$(pwd)/../

function buildApp() {

    echo "----------- create build directory  ----------------------"
    mkdir -p $root/build/warehouse
    echo "build directory created sucessfully"

    echo ""
    echo "----------- build $1 go app -----------------------"
    cd $root/app/$1/api

    go mod vendor
    rm -rf $root/build/$1/app
    go build -o $root/build/$1/app

    rm -rf $root/build/$1/config.json
    cp $root/app/$1/api/config.json $root/build/$1/config.json

    echo "$1 go app built sucessfully"

    echo ""
    echo "----------- build $1 angular app ------------------"
    cd $root/app/$1/web

    npm install
    rm -rf $root/build/$1/www/
    ng build --prod --output-path $root/build/$1/www/
    echo "$1 angular app built sucessfully"
    echo ""
}

buildApp warehouse