#!/bin/bash

root=$(pwd)/../

echo "----------- create build directory  ---------------"
mkdir -p $root/build/warehouse
echo "build directory created sucessfully"

echo ""
echo "----------- build warehouse go app ---------------"
cd $root/app/warehouse/api

go mod vendor
rm -rf $root/build/warehouse/app
go build -o $root/build/warehouse/app

rm -rf $root/build/warehouse/config.json
cp $root/app/warehouse/api/config.json $root/build/warehouse/config.json

echo "warehouse go app built sucessfully"

echo ""
echo "----------- build warehouse angular app ---------------"
cd $root/app/warehouse/web

npm install
rm -rf $root/build/warehouse/www/
ng build --prod --output-path $root/build/warehouse/www/
echo "warehouse angular app built sucessfully"
echo ""