#!/bin/bash

if [[ $1 == 'netup' ]]
then
    echo
    echo "-----------------------------------------------------------------------------"
    echo "Executing command: ./minifab netup -e true -s couchdb -o admin.truware.com"
    echo "-----------------------------------------------------------------------------"
    echo

    cd ../network
    ./minifab netup -e true -s couchdb -o admin.truware.com

elif [[ $1 == 'up' ]]
then
    echo "---------------------  copy chaincode 'warehouse --------------------- "
    ./copy_cc warehouse
    echo "-copy chaincode done"
    echo

    echo
    echo "------------------------------------------------------------------------------------------------"
    echo "Executing command: ./minifab up -e true -s couchdb -c mychannel -n warehouse -o admin.truware.com"
    echo "------------------------------------------------------------------------------------------------"
    echo

    cd ../network
     ./minifab up -e true -s couchdb -c mychannel -n warehouse -p '"InitLedger"' -o admin.truware.com

elif [[ $1 == 'down' ]]
then
    echo
    echo "------------------------------------------------------"
    echo "Executing command: ./minifab down -o admin.truware.com"
    echo "------------------------------------------------------"
    echo

    cd ../network
    ./minifab down -o admin.truware.com

elif [[ $1 == 'cleanup' ]]
then
    echo
    echo "---------------------------------------------------------"
    echo "Executing command: ./minifab cleanup -o admin.truware.com"
    echo "---------------------------------------------------------"
    echo

    cd ../network
    ./minifab cleanup -o admin.truware.com

else
    echo "Plese enter the command line"
    echo " * netup - make the network up with creating channel and deploying chaincode. (first time onwards)"
    echo " * up - make the network up with creating 'mychannel' and 'simple' chaincode (first time)"
    echo " * down - make the network down"
    echo " * cleanup - cleans everything including data and nodes"
fi